### ISSUE TITLE
Allied objectives aren't properly considered during summon's focus 

### ISSUE THREAD

**Issue by jonathanmclaus** [tsmigiel/haven-helper#28]
![image](https://github.com/user-attachments/assets/f1a64673-50df-4c3d-ab18-bb9c85695c05)

In this example, I have a summon that is not flying. The image shows it finding focus on the night demon in the lower right and moving through the objective towards it. The objective is allied, but the summon would still not be allowed to move through it. 

Under Move on p. 24 of the rulebook:

> Figures can move through allies but cannot move through enemies, obstacles, objectives, or walls.

The [FAQ](https://cephalofairgames.github.io/frosthaven-faq/#page_57) further clarifies:

> **Can I move through an allied Objective?**
>  Not without Jump or Fly. (Note - this is covered under Move abilities in the rulebook on page 24, not under Objectives.)

Therefore, the summon should move to the bottom left, finding focus at (1, 15) with 8 movement away.

I have not checked whether an enemy monster can find focus by moving through an enemy objective, but I would guess that has a similar bug.

**Comment by tsmigiel** [comment]
Ahh, thanks! I'll fix it.

**Comment by tsmigiel** [comment]
The fix is live.

Yes the issue would have happened for monsters too and is addressed by the same change.

Interestingly, I had originally implemented this for FH because the rules say "Objectives are treated as figures ... and not treated as obstacles.", but I never double checked that against the move rules as you quoted above. I imagine that is why a FAQ exists.
